### ISSUE TITLE
Update countries.json

### ISSUE THREAD

**Issue by GazzaHazza** [sallar/country-tools#3]
`countries.json` is out of date according to [mledoze/countries](https://github.com/mledoze/countries/blob/master/countries.json).

**Comment by GazzaHazza** [comment]
Update countries.json

**Comment by sallar** [comment]
Hi @GazzaHazza, sorry I missed this issue due to email settings. Did you close your PR?

**Comment by GazzaHazza** [comment]
@sallar - I did as it was 18 months or so old so was abit out of date.
